
const skills: string[] = [
    "JavaScript", 
    "TypeScript", 
    "Java", 
    "Python", 
    "PHP", 
    "HTML", 
    "CSS", 
    "Node.js", 
    "Express.js", 
    "React", 
    "Redux", 
    "Flask", 
    "Bootstrap", 
    "Unit Testing",
    "Integration Testing", 
    "Jest", 
    "Jasmine", 
    "Debugging", 
    "Git", 
    "GitHub", 
    "Version Control", 
    "Continuous Integration (CI)", 
    "Continuous Delivery (CD)", 
    "Docker", 
    "Object Oriented Programming (OOP)", 
    "CRUD APIs", 
    "RESTful APIs", 
    "Data Structures", 
    "Algorithms", 
    "Relational Database",
    "noSQL Database",
    "MySQL", 
    "PostgreSQL", 
    "MongoDB", 
    "Software Development Life Cycle (SDLC)"
]

export default skills;